# Generated by Django 5.0.3 on 2024-03-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curds', '0001_initial'),
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='bio',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curds.curd'),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employe.employeemodel'),
        ),
    ]
